In [1]:
import numpy as np

In [2]:
# a NumPy array with 100 equally spaced values in the range 0 through 100(not including 100).
a=np.arange(0,100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [3]:
#a NumPy array with 10 equally spaced values in the range 0 through 10
b=np.arange(0,100,10)
print(b)

[ 0 10 20 30 40 50 60 70 80 90]


In [4]:
#a NumPy array in the range 0 through 10 (inclusive) with values spaced at 0.
c=np.linspace(0,10,100)
print(c)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [5]:
#a random two-dimensional array with the dimensions 10 b
d=np.random.rand(10,10)
print(d)

[[0.91652459 0.15291994 0.48528488 0.26611736 0.85644846 0.22679488
  0.24592645 0.12822536 0.24470238 0.03881856]
 [0.05351229 0.91903279 0.57833919 0.13409643 0.59157872 0.48776576
  0.12855361 0.11454023 0.96070026 0.44397248]
 [0.87495165 0.45512109 0.91400076 0.03364225 0.19744119 0.18484813
  0.09157844 0.2339297  0.65137788 0.07967827]
 [0.48759364 0.6272857  0.6818421  0.21317147 0.24304894 0.99610673
  0.77253229 0.94169132 0.94659221 0.09995669]
 [0.46060872 0.54155542 0.5047321  0.19549216 0.00949409 0.5830351
  0.40765857 0.92025111 0.42908497 0.64970417]
 [0.57032854 0.37718225 0.30451786 0.61498354 0.94527283 0.49851873
  0.29711464 0.33915468 0.51025223 0.29870981]
 [0.49731662 0.49390433 0.23371616 0.65152606 0.10204141 0.09804816
  0.52424713 0.13187208 0.01223375 0.894568  ]
 [0.75588823 0.62445101 0.88780225 0.72827558 0.75475602 0.63039912
  0.980505   0.45504006 0.83503052 0.87527853]
 [0.64882523 0.17126351 0.7251921  0.23208266 0.55521707 0.88001678
  0.36350816 

In [6]:
#reshape a so that it is a two-dimensional array with the dimensions 10 by 10

a=np.reshape(a,(10,10))
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [7]:
#shows the fourth row and the fifth column, thus getting 45
print(a[4,5])

45


In [8]:
#shows the 4th row
print(a[4])

[40 41 42 43 44 45 46 47 48 49]


In [9]:
#sum of d
print(np.sum(d))

48.98747190742165


In [10]:
#sum of a
print(np.max(a))

99


In [11]:
#transpose of b
print(np.transpose(b))

[ 0 10 20 30 40 50 60 70 80 90]


In [12]:
#adding a and d
print(a+d)

[[ 0.91652459  1.15291994  2.48528488  3.26611736  4.85644846  5.22679488
   6.24592645  7.12822536  8.24470238  9.03881856]
 [10.05351229 11.91903279 12.57833919 13.13409643 14.59157872 15.48776576
  16.12855361 17.11454023 18.96070026 19.44397248]
 [20.87495165 21.45512109 22.91400076 23.03364225 24.19744119 25.18484813
  26.09157844 27.2339297  28.65137788 29.07967827]
 [30.48759364 31.6272857  32.6818421  33.21317147 34.24304894 35.99610673
  36.77253229 37.94169132 38.94659221 39.09995669]
 [40.46060872 41.54155542 42.5047321  43.19549216 44.00949409 45.5830351
  46.40765857 47.92025111 48.42908497 49.64970417]
 [50.57032854 51.37718225 52.30451786 53.61498354 54.94527283 55.49851873
  56.29711464 57.33915468 58.51025223 59.29870981]
 [60.49731662 61.49390433 62.23371616 63.65152606 64.10204141 65.09804816
  66.52424713 67.13187208 68.01223375 69.894568  ]
 [70.75588823 71.62445101 72.88780225 73.72827558 74.75475602 75.63039912
  76.980505   77.45504006 78.83503052 79.87527853]
 

In [13]:
#multiplying a*d
print(a*d)

[[ 0.          0.15291994  0.97056976  0.79835209  3.42579386  1.13397439
   1.47555871  0.89757752  1.95761906  0.34936701]
 [ 0.53512288 10.10936065  6.94007027  1.74325359  8.28210205  7.31648635
   2.0568577   1.94718388 17.29260473  8.43547705]
 [17.49903299  9.55754288 20.1080168   0.77377177  4.7385886   4.62120332
   2.38103939  6.31610201 18.23858053  2.3106697 ]
 [14.62780906 19.44585671 21.8189473   7.03465842  8.26366404 34.86373552
  27.81116253 34.84257868 35.97050394  3.89831105]
 [18.42434861 22.20377214 21.19874829  8.4061629   0.41773978 26.23657934
  18.75229436 43.25180212 20.59607875 31.83550422]
 [28.51642695 19.23629461 15.83492859 32.59412772 51.04473285 27.41853024
  16.63841963 19.33181695 29.59462947 17.62387867]
 [29.83899734 30.12816436 14.49040172 41.04614154  6.53065038  6.37313017
  34.60031067  8.83542932  0.83189523 61.72519229]
 [52.91217586 44.33602184 63.92176222 53.16411769 55.85194578 47.27993395
  74.51838024 35.03808442 65.1323807  69.14700364]


In [14]:
#dot product a nd d
print(np.dot(a,d))

[[ 22.84243902  17.38818402  29.19435666  24.55550533  21.03617785
   27.36724893  23.35259801  20.99462686  24.68626561  27.21359432]
 [ 77.07176261  62.03781979  90.99587784  65.24268819  68.27688993
   80.61760012  66.67995214  62.84584267  81.1948626   73.54241982]
 [131.30108619 106.68745555 152.79739902 105.92987104 115.51760201
  133.86795131 110.00730626 104.69705847 137.70345959 119.87124532]
 [185.53040978 151.33709131 214.5989202  146.6170539  162.75831409
  187.1183025  153.33466038 146.54827427 194.21205657 166.20007082]
 [239.75973337 195.98672708 276.40044137 187.30423676 209.99902617
  240.3686537  196.66201451 188.39949008 250.72065356 212.52889632]
 [293.98905696 240.63636284 338.20196255 227.99141961 257.23973825
  293.61900489 239.98936863 230.25070588 307.22925055 258.85772182]
 [348.21838054 285.2859986  400.00348373 268.67860247 304.48045033
  346.86935608 283.31672275 272.10192169 363.73784753 305.18654733]
 [402.44770413 329.93563437 461.80500491 309.36578533 3